version: "3.1"

services:

  graphql_postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    tty: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - graphql_net

  migrate:
    image: migrate/migrate
    build: .
    volumes:
      - ./scripts/migrations:/migrations
    env_file:
      - .env
    restart: on-failure
    networks:
      - graphql_net

networks:
  graphql_net: